name: KDR-PE
version: 1.0.3-beta1
author: Terpz710
api: 5.0.0
main: Terpz710\KDRPE\Main
description: A KDR system.
softdepend: ScoreHud

permissions:
  kdr-pe.command.kdr:
    description: Allows the player to see their KDR.
    default: true
  kdr-pe.command.seekdr:
    description: Allows the player to see other players KDR.
    default: true
  kdr-pe.command.topkill:
    description: Allows the player to see the top kills.
    default: true
  kdrpe.command.killstreak:
    description: Allows the player to see their kill streak.
    default: true
  kdrpe.command.seekillstreak:
    description: Allows the player to see other players kill streak.
    default: true
  kdrpe.command.topkillft:
    description: Allows the OP to add/remove the top kill floating text.
    default: op
