name: KDR-PE
version: 1.0.0
author: Terpz710
api: 5.0.0
main: Terpz710\KDRPE\Main

permissions:
  kdr-pe.kdr:
    description: Allows anyone to use KDR command.
    default: true
  kdr-pe.topkill:
    description: Allows anyone to use top kill command.
    default: true
  kdr-pe.topkillft:
    description: Allows only OP to add topkill leaderboard floating text.
    default: op
