name: KDR-PE
version: 1.0.6
author: Terpz710
api: 5.44.2
main: terpz710\kdrpe\Core
virions:
  - Commando
  - UpdateNotifier
  - ConfigUpdater

permissions:
  kdrpe.stats:
    default: true
  kdrpe.otherstats:
    default: true
  kdrpe.leaderboard:
    default: true
  kdrpe.ftext.leaderboard:
    default: op